title: Öffentliche Bücherschränke
description: Karte mit öffentlichen Bücherschränken basierend auf OSM Daten.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
    values:
      permalink: ""

theme: jekyll-theme-minimal