plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
    values:
      permalink: ""
      lang: "en"
      title: Public bookcases
      description: Map with public bookcases based on OSM data.
  - scope:
      path: "de/README.md"
    values:
      permalink: "de"
      lang: "de"
      title: Öffentliche Bücherschränke
      description: Karte mit öffentlichen Bücherschränken basierend auf OSM Daten.
