title: Public bookcases

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "README.md"
    values:
      permalink: ""
      lang: "en"
  - scope:
      path: "de/README.md"
    values:
      permalink: "de"
      lang: "de"
