defaults:
  - scope:
      path: "README.md"
    values:
      permalink: ""
      lang: "en"
      title: "Public bookcases"
      description: "A map with public bookcases for book exchange. The map is based on OSM data."
  - scope:
      path: "de/README.md"
    values:
      permalink: "de"
      lang: "de"
      title: "Öffentliche Bücherschränke"
      description: "Eine Karte mit öffentlichen Bücherschränken für das Tauschen von Büchern. Die Karte basiert auf OSM Daten."
