defaults:
  - scope:
      path: "docs/README.md"
    values:
      lang: "en"
      title: "Public bookcases"
      description: "A map with public bookcases for book exchange. The map is based on OSM data."
      base: "/"
